Feat/ev 927/revision page
SuelenLaffinWarren/EverestCryptoWallet pull request #7
Opened 2022-10-10 18:06 UTC by SuelenLaffinWarren

## Card 8 - Tela de Revisão

✅ Revisão de dados de acordo com a página de conversão;
✅ Utilização de Riverpood;
✅ Navegação funcional;

Extra:
✅ Utilização de animação na tela de sucesso, e utilização de animação entre a transição das páginas.

## Prints:

https://user-images.githubusercontent.com/113142506/194927662-5e9d2509-5687-4159-af42-9d3a7bb8b0a4.mp4

2022-10-10 18:59 UTC, guilhermeqmaia approved these changes

2022-10-10 18:59 UTC, guilhermeqmaia commented on lib/conversion/view/conversion_screen.dart
> +            crypto: widget.args.cryptoData,
Se você recebe cryptoData como argumento para essa página, acredito que não tenha a necessidade de chamar o provider após o build e nem de usar o cryptoData.when para construir a página com os nós.

Caso você queira ao invés de passar por argumentos, usar o cryptoData como uma List<(CryptoViewData)>, você pode passar no construtor das páginas **cryptoData.asData!.value**

Embora tenha um Null Check Operator, ele vai funcionar tranquilamente porque a requisição já foi feita na tela portfólio.

2022-10-10 18:59 UTC, guilhermeqmaia commented on lib/conversion/widgets/row_convert_buttons.dart
> +            onPressed: () {},
Caso você não pretenda atribuir uma função para essa botão, da para deixar apenas um Icon msm

2022-10-10 18:59 UTC, guilhermeqmaia commented on lib/revision/widgets/app_bar_revision.dart
> +    return AppBar(
Essa AppBar aparece várias vezes em telas diferentes, como em Detalhes, Conversão e Revisão, a única coisa que muda é o nome, uma sugestão seria extrair e usar como um template

2022-10-10 20:38 UTC, SuelenLaffinWarren commented on lib/revision/widgets/app_bar_revision.dart
> +    return AppBar(
Obrigada pelas sugestões, já estou arrumando!

2022-10-11 11:57 UTC, julialuciani approved these changes

2022-10-11 11:57 UTC, julialuciani commented on lib/portfolio/provider/portfolio_model_provider.dart
> +  // void variationChange(int time) {
Cometários que podem ser apagados

2022-10-13 11:19 UTC, julialuciani approved these changes

2022-10-13 11:19 UTC, julialuciani commented on lib/conversion/widgets/row_convert_buttons.dart
> +          Padding(
Você tem aqui um padding como child de um padding, em vez disso use um padding e se preciso aumente o tamanho dele.

2022-10-13 11:19 UTC, julialuciani commented on lib/crypto_details/widgets/body_crypto_details.dart
> +                      thickness: 1,
Em vez de ter duas sizedbox uma antes e outra depois da divider, você pode optar por usar o parâmetro height do divider e colocar um 20 por exemplo

2022-10-13 11:19 UTC, julialuciani commented on lib/crypto_details/widgets/body_crypto_details.dart
> +                    const SizedBox(
Aqui é a mesma questão

2022-10-13 11:19 UTC, julialuciani commented on lib/crypto_details/widgets/body_crypto_details.dart
> +                      height: 10,
Aqui tbm

2022-10-13 11:19 UTC, julialuciani commented on lib/portfolio/widgtes/crypto_list_tile.dart
> +                : SizedBox(
Não faz sentido ter essa sizedBox com um container dentro dela, como não recebe nenhum parâmetro não está fazendo praticamente nada.

2022-10-13 11:19 UTC, julialuciani commented on lib/portfolio/widgtes/crypto_list_tile.dart
> +                : SizedBox(
Aqui também

2022-10-13 11:19 UTC, julialuciani commented on lib/revision/view/revision_screen.dart
> +            child: SingleChildScrollView(
O SingleChildScrollView tem o próprio parâmetro de padding nele, logo você poderia tirar esse padding e colocar direto no SingleChildScrollView

2022-10-13 11:19 UTC, julialuciani commented on lib/revision/widgets/body_revision.dart
> +        const SizedBox(
Aqui dá para colocar height no divider

2022-10-13 11:19 UTC, julialuciani commented on lib/revision/widgets/body_revision.dart
> +        const SizedBox(
Aqui também

2022-10-13 11:19 UTC, julialuciani commented on lib/revision/widgets/body_revision.dart
> +          height: 10,
Aqui

2022-10-13 11:19 UTC, julialuciani commented on lib/revision/widgets/body_revision.dart
> +        const SizedBox(
Você pode trocar essa sizedBox por um padding, que seria mais responsivo, ao aumentar também o padding top para remover essa sizedBox logo acima que se tornaria desnecessária.

2022-10-13 11:48 UTC, SuelenLaffinWarren commented on lib/revision/widgets/body_revision.dart
> +        const SizedBox(
Obrigada pelas sugestões!!! Realizei as alterações e fiz o commit, porém foram pra branch da tela de movimentações

2022-10-14 12:27 UTC, CarlosTSIlva requested changes
assim q corrigir me chama

2022-10-14 12:27 UTC, CarlosTSIlva commented on lib/conversion/provider/conversion_provider.dart
> +  ),
neh melhor  vc usar sem required e declarar os valores iniciais na própria classe?

2022-10-14 12:27 UTC, CarlosTSIlva commented on lib/crypto_details/view/crypto_details_screen.dart
> +                  '/portfolio',
se ta usando rodas na classe daria pra fazer 
portfolios.routes ....

2022-10-14 12:27 UTC, CarlosTSIlva commented on lib/portfolio/provider/portfolio_model_provider.dart
> +  // }
os comentarios apagar

2022-10-14 13:01 UTC, merged